name: Build Image
on:
- workflow_dispatch
- push

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup dependencies
      run: |
        git clone https://github.com/cachiusa/linux-build-scripts.git build
        ./build/setup/debian.sh
        sudo apt-get install llvm

    - name: Restore ccache
      id: restore-ccache
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/out/.ccache
        key: ccache-${{ github.run_id }}
        restore-keys: ccache-

    - name: Restore ThinLTO cache
      id: restore-thinltocache
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/out/.thinlto-cache
        key: thinlto-${{ github.run_id }}
        restore-keys: thinlto-

    - name: Run build
      run: |
        time BUILD_CONFIG=build/DEVICE.veux.config ./build/build.sh -j2

    # - name: Upload zip
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ env.ARTIFACTNAME }}
    #     path: "AnyKernel3/"

    - name: Save ccache
      if: always() && steps.restore-ccache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/out/.ccache
        key: ccache-${{ github.run_id }}

    - name: Save ThinLTO cache
      if: always() && steps.restore-thinltocache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/out/.thinlto-cache
        key: thinlto-${{ github.run_id }}
