name: Build Image
on:
- workflow_dispatch
- push

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: Setup dependencies
      run: |
        git clone https://github.com/cachiusa/linux-build-scripts.git build
        ./build/setup/debian.sh
        sudo apt-get install clang clang-tools llvm lld

    - name: ccache
      uses: actions/cache@v6
      with:
        path: ${{ github.workspace }}/out/.ccache
        key: ccache-${{ github.run_id }}
        restore-keys: ccache-

    - name: ThinLTO cache
      uses: actions/cache@v6
      with:
        path: ${{ github.workspace }}/out/.thinlto-cache
        key: thinlto-${{ github.run_id }}
        restore-keys: thinlto-

    - name: Run build
      run: |
        ccache --set-config=cache_dir="$(pwd)/out/.ccache"
        ccache --set-config=max_size=2G
        ccache --set-config=compression=false
        time BUILD_CONFIG=build/DEVICE.veux.config ./build/build.sh -j2

    # - name: Upload zip
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ env.ARTIFACTNAME }}
    #     path: "AnyKernel3/"
